name: myapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Use a stable Dart version

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.8
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.1.0
  video_player: ^2.8.6
  provider: ^6.1.2
  http: ^1.1.0
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.3.0 # Or latest version

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
    - assets/icon.png
    - assets/notif.png
    - assets/ed.png
    - assets/home.png
    - assets/kendrick.png
    - assets/solana.png
    - assets/calendar.png
    - assets/bg.png
    - assets/bg2.png
    - assets/logo.png
    - assets/aquacultura.mp4
    - assets/watertemp.png
    - assets/phlevel.png
    - assets/nutrietncontrol.png
    - assets/cropinsights.png
    - assets/cropinsightsicon.png
    - assets/mytaskicon.png
    - assets/teamicon.png
    - assets/eye.png
    - assets/view.png
    - assets/cogwheel.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logos/aclogo.png"
  adaptive_icon_foreground: "assets/logos/aclogo.png"
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logos/aclogo.png
  android: true
  ios: true # Set to false if you don't want to generate for iOS initially
  # You can add more platform-specific configurations if needed
  # android_12:
  #   image: assets/logos/aclogo_android12.png
  #   color: "#FFFFFF"
